export const PERMISSIONS = [
  "institutions.view",
  "institutions.manage",
  "users.view",
  "users.create",
  "users.update",
  "users.delete",
  "students.view",
  "students.create",
  "students.update",
  "students.delete",
  "teachers.view",
  "teachers.create",
  "teachers.update",
  "teachers.delete",
  "applicants.view",
  "applicants.create",
  "applicants.update",
  "applicants.delete",
  "programs.view",
  "programs.create",
  "programs.update",
  "programs.delete",
  "courses.view",
  "courses.create",
  "courses.update",
  "courses.delete",
  "classes.view",
  "classes.create",
  "classes.update",
  "classes.delete",
  "enrollments.view",
  "enrollments.create",
  "enrollments.update",
  "enrollments.delete",
  "class_transfers.view",
  "class_transfers.create",
  "schedules.view",
  "schedules.create",
  "schedules.update",
  "schedules.delete",
  "attendance.view",
  "attendance.create",
  "attendance.update",
  "assessments.view",
  "assessments.create",
  "assessments.update",
  "assessments.delete",
  "grades.view",
  "grades.create",
  "grades.update",
  "grades.validate",
  "payments.view",
  "payments.create",
  "payments.update",
  "refunds.view",
  "refunds.create",
  "expenses.view",
  "expenses.create",
  "expenses.update",
  "expenses.delete",
  "documents.view",
  "documents.create",
  "documents.delete",
  "certificates.view",
  "certificates.create",
  "certificates.verify",
  "notifications.view",
  "notifications.create",
  "reports.view",
  "audit.view",
  "settings.view",
  "settings.manage",
  "hr.view",
  "hr.create",
  "hr.update",
  "hr.delete",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLES = [
  "super_admin",
  "direction",
  "administration",
  "scolarite",
  "comptabilite",
  "rh",
  "formateur",
  "etudiant",
] as const;

export type Role = (typeof ROLES)[number];
